version: '2'
services:
    manager:
        image: asperathos_manager
        ports:
            - 1500:1500
        environment:
            - KUBECONFIG=/.kube/config
        volumes:
            - ${KUBECONFIG}/..:/.kube
    controller:
        image: asperathos_controller
        ports:
            - 5000:5000
        environment:
            - KUBECONFIG=/.kube/config
        volumes:
            - ${KUBECONFIG}/..:/.kube
    monitor:
        image: asperathos_monitor
        ports:
            - 5001:5001
        environment:
            - KUBECONFIG=/.kube/config
        volumes:
            - ${KUBECONFIG}/..:/.kube
    visualizer:
        image: asperathos_visualizer
        ports:
            - 5002:5002
        environment:
            - KUBECONFIG=/.kube/config
        volumes:
            - ${KUBECONFIG}/..:/.kube
